# Site
title: 瑞铭的博客
description: 测试
github: https://github.com/ruiming
google: https://plus.google.com/115149019958723046324

# Pagination
pagination:
  index_page: 5

# User


# session
secret: 120rhub579175afigbj03t0135b09u60