# 请不要在初始化前修改此文件的内容, 初始化过程会重写这个文件
# Site
title: 某人的博客
description: 某人的博客
github: 
google: 

# Pagination
pagination:
  index_page: 5

# Markdown
editor:
  minHeight: 600
  height:

# User
username: test
password: test