# Site
title: r
description: r
avatar: /img/avatar.png
github: r
google: 

# Pagination
pagination:
  index_page: 5

# Markdown
editor:
  minHeight: 600
  height:

# User
username: r
password: r

# Deploy
remote: 
branch: 

# Other
env: development
key: 
cert: 
ca: 