# Site
title: 某人的博客
description: 某人的博客
avatar: /img/avatar.png
github: /
google: /

# Pagination
pagination:
  index_page: 5

# Markdown
editor:
  minHeight: 600
  height:

# disqus
disqus: ruiming
sites: https://ruiming.me

# google-analytics
gaid: UA-81637252-1

# User
username: 某人
password: 某人

# Deploy
remote: 
branch: 

# Other
env: development
key: 
cert: 
ca: 