# Site
title: 某人的博客
description: 某人的博客
avatar: /img/avatar.png
github: 
google: 

# Pagination
pagination:
  index_page: 5

# Markdown
editor:
  minHeight: 600
  height:

# User
username: 
password: 

# Deploy
remote: 