# Site
title: 某人的博客
description: 某人的博客
avatar: /img/avatar.png
github: /
google: /

# Pagination
pagination:
  index_page: 6

# Markdown
editor:
  minHeight: 600
  height:

# disqus
disqus:
sites:

# google-analytics
gaid: 

# User
username: 某人
password: 某人

# Deploy
remote: 
branch: 

# Other
env: production
key: 
cert: 
ca: 